# Generated by Django 4.2 on 2023-07-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20)),
                ('Phone_no', models.IntegerField(max_length=20)),
                ('Messege', models.TextField(max_length=500)),
            ],
        ),
    ]
